apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  namespace: onlineboutique
spec:
  selector:
    matchLabels:
      app: loadgenerator
  replicas: 1
  template:
    metadata:
      labels:
        app: loadgenerator
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: "" #kubernetes.io/hostname: node2.cluster.ilabt-imec-be.wall1.ilabt.iminds.be #dedicated: master
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      initContainers:
      - command:
        - /bin/sh
        - -exc
        - |
          echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
          STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
          if test $STATUSCODE -ne 200; then
              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
              exit 1
          fi
        name: frontend-check
        image: busybox:latest
        env:
        - name: FRONTEND_ADDR
          value: "frontend:80"
      containers:
      - name: main
        image: jpedro1992/loadgenerator:v0.0.2 #jpedro1992/loadgenerator:v0.0.1 #gcr.io/google-samples/microservices-demo/loadgenerator:v0.3.1
        ports:
        - containerPort: 8089
        env:
        - name: FRONTEND_ADDR
          value: "frontend:80"
        - name: USERS
          value: "10"
        resources:
          requests:
            cpu: 300m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: loadgenerator
  namespace: onlineboutique
spec:
  type: ClusterIP
  selector:
    app: loadgenerator
  ports:
  - name: locust
    port: 8089
    targetPort: 8089
---
